import { execFileSync } from "node:child_process";
import { lstatSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const siteDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoDir = resolve(siteDir, "../..");
const outputPath = resolve(siteDir, "convex/repoSnapshot.generated.ts");

const excludedPath = /(?:^|\/)(?:node_modules|dist|build|coverage|\.git|_generated)(?:\/|$)/;
const excludedFile = /(?:^|\/)(?:\.env(?:\..*)?|bun\.lock|[^/]+\.lock|repoSnapshot\.generated\.ts)$/;
const excludedExtension = /\.(?:png|jpe?g|gif|webp|ico|woff2?|ttf|otf|pdf|zip|gz|tgz|bz2|xz|wasm|map|pem|key|p12|pfx)$/i;
const maxFileBytes = 512 * 1024;

const git = (...args: string[]) =>
  execFileSync("git", args, { cwd: repoDir, encoding: "utf8" }).trim();

const revision = git("rev-parse", "HEAD");
const dirty = git("status", "--porcelain", "--untracked-files=no").length > 0;
const files: Record<string, string> = {};
let skippedLarge = 0;
let skippedBinary = 0;
let skippedSymlink = 0;

for (const path of git("ls-files").split("\n").filter(Boolean)) {
  if (excludedPath.test(path) || excludedFile.test(path) || excludedExtension.test(path)) continue;
  const absolutePath = resolve(repoDir, path);
  const stat = lstatSync(absolutePath);
  if (stat.isSymbolicLink() || !stat.isFile()) {
    skippedSymlink += 1;
    continue;
  }
  const size = stat.size;
  if (size > maxFileBytes) {
    skippedLarge += 1;
    continue;
  }
  const bytes = readFileSync(absolutePath);
  if (bytes.includes(0)) {
    skippedBinary += 1;
    continue;
  }
  files[`/${path}`] = bytes.toString("utf8");
}

const snapshot = {
  revision: `${revision}${dirty ? "-dirty" : ""}`,
  fileCount: Object.keys(files).length,
  byteCount: Object.values(files).reduce((total, value) => total + Buffer.byteLength(value), 0),
  skippedLarge,
  skippedBinary,
  skippedSymlink,
  files,
};

const source = `// Generated by scripts/generate-repo-snapshot.ts. Do not edit.\nexport default ${JSON.stringify(snapshot)} as const;\n`;
writeFileSync(outputPath, source);
console.log(
  `repo snapshot ${snapshot.revision.slice(0, 18)}: ${snapshot.fileCount} files, ${snapshot.byteCount} bytes`,
);
